stages:
    - build
    - test
    - test_sonar
    - pre_package
    - package
    - deploy

variables:
    MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
    DOCKER_IMAGE_TAGGED: helmholtzcloud/marketplace:$CI_COMMIT_SHA
    DOCKER_IMAGE_LATEST: helmholtzcloud/marketplace:latest

cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
        - ".m2/repository"

include:
    - local: .gitlab/ci/create-docker-image-ci.yml
    - local: .gitlab/ci/static-code-analysis.yml
