name: Docker

on:
    push:
        branches: [ master ]
    release:
        types: [published]

jobs:
    docker_build:
        name: Create and push Docker image to Docker Hub
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v2
            - name: Set up JDK 11
              uses: actions/setup-java@v1
              with:
                  java-version: 11
            - name: Build with Maven
              run: mvn -B package --file pom.xml
            - name: Push to Docker Hub
              uses: docker/build-push-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
                  repository: helmholtzcloud/marketplace
                  tag_with_ref: true
                  tags: latest
